---
# deploy untuk mindahin otomatis ke hoster
deployment:
  tasks:
    - export DEPLOYPATH=/home/user (ganti pake nama user)/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
# di hoster untuk update perubahan klik update from remote terus deploy HEAD commit, kemudian refresh websitenya
